export interface Airport {
  iata: string;
  name: string;
  city: string;
  state?: string;
  country: string;
}

export const airports: Airport[] = [
  // United States
  { iata: "ATL", name: "Hartsfield-Jackson Atlanta International", city: "Atlanta", state: "GA", country: "US" },
  { iata: "LAX", name: "Los Angeles International", city: "Los Angeles", state: "CA", country: "US" },
  { iata: "ORD", name: "O'Hare International", city: "Chicago", state: "IL", country: "US" },
  { iata: "DFW", name: "Dallas/Fort Worth International", city: "Dallas-Fort Worth", state: "TX", country: "US" },
  { iata: "DEN", name: "Denver International", city: "Denver", state: "CO", country: "US" },
  { iata: "JFK", name: "John F. Kennedy International", city: "New York", state: "NY", country: "US" },
  { iata: "SFO", name: "San Francisco International", city: "San Francisco", state: "CA", country: "US" },
  { iata: "SEA", name: "Seattle-Tacoma International", city: "Seattle", state: "WA", country: "US" },
  { iata: "LAS", name: "Harry Reid International", city: "Las Vegas", state: "NV", country: "US" },
  { iata: "MCO", name: "Orlando International", city: "Orlando", state: "FL", country: "US" },
  { iata: "EWR", name: "Newark Liberty International", city: "Newark", state: "NJ", country: "US" },
  { iata: "MIA", name: "Miami International", city: "Miami", state: "FL", country: "US" },
  { iata: "PHX", name: "Phoenix Sky Harbor International", city: "Phoenix", state: "AZ", country: "US" },
  { iata: "IAH", name: "George Bush Intercontinental", city: "Houston", state: "TX", country: "US" },
  { iata: "BOS", name: "Boston Logan International", city: "Boston", state: "MA", country: "US" },
  { iata: "MSP", name: "Minneapolis-Saint Paul International", city: "Minneapolis", state: "MN", country: "US" },
  { iata: "FLL", name: "Fort Lauderdale-Hollywood International", city: "Fort Lauderdale", state: "FL", country: "US" },
  { iata: "DTW", name: "Detroit Metropolitan Wayne County", city: "Detroit", state: "MI", country: "US" },
  { iata: "PHL", name: "Philadelphia International", city: "Philadelphia", state: "PA", country: "US" },
  { iata: "LGA", name: "LaGuardia", city: "New York", state: "NY", country: "US" },
  { iata: "BWI", name: "Baltimore/Washington International", city: "Baltimore", state: "MD", country: "US" },
  { iata: "SLC", name: "Salt Lake City International", city: "Salt Lake City", state: "UT", country: "US" },
  { iata: "IAD", name: "Washington Dulles International", city: "Washington", state: "DC", country: "US" },
  { iata: "DCA", name: "Ronald Reagan Washington National", city: "Washington", state: "DC", country: "US" },
  { iata: "SAN", name: "San Diego International", city: "San Diego", state: "CA", country: "US" },
  { iata: "TPA", name: "Tampa International", city: "Tampa", state: "FL", country: "US" },
  { iata: "PDX", name: "Portland International", city: "Portland", state: "OR", country: "US" },
  { iata: "HNL", name: "Daniel K. Inouye International", city: "Honolulu", state: "HI", country: "US" },
  { iata: "STL", name: "St. Louis Lambert International", city: "St. Louis", state: "MO", country: "US" },
  { iata: "BNA", name: "Nashville International", city: "Nashville", state: "TN", country: "US" },
  { iata: "AUS", name: "Austin-Bergstrom International", city: "Austin", state: "TX", country: "US" },
  { iata: "SJC", name: "San Jose International", city: "San Jose", state: "CA", country: "US" },
  { iata: "DAL", name: "Dallas Love Field", city: "Dallas", state: "TX", country: "US" },
  { iata: "HOU", name: "William P. Hobby", city: "Houston", state: "TX", country: "US" },
  { iata: "OAK", name: "Oakland International", city: "Oakland", state: "CA", country: "US" },
  { iata: "SMF", name: "Sacramento International", city: "Sacramento", state: "CA", country: "US" },
  { iata: "RSW", name: "Southwest Florida International", city: "Fort Myers", state: "FL", country: "US" },
  { iata: "RDU", name: "Raleigh-Durham International", city: "Raleigh", state: "NC", country: "US" },
  { iata: "CLE", name: "Cleveland Hopkins International", city: "Cleveland", state: "OH", country: "US" },
  { iata: "MCI", name: "Kansas City International", city: "Kansas City", state: "MO", country: "US" },
  { iata: "IND", name: "Indianapolis International", city: "Indianapolis", state: "IN", country: "US" },
  { iata: "PIT", name: "Pittsburgh International", city: "Pittsburgh", state: "PA", country: "US" },
  { iata: "CMH", name: "John Glenn Columbus International", city: "Columbus", state: "OH", country: "US" },
  { iata: "SAT", name: "San Antonio International", city: "San Antonio", state: "TX", country: "US" },
  { iata: "SJU", name: "Luis Muñoz Marín International", city: "San Juan", state: "PR", country: "US" },
  { iata: "CVG", name: "Cincinnati/Northern Kentucky International", city: "Cincinnati", state: "OH", country: "US" },
  { iata: "JAX", name: "Jacksonville International", city: "Jacksonville", state: "FL", country: "US" },
  { iata: "MSY", name: "Louis Armstrong New Orleans International", city: "New Orleans", state: "LA", country: "US" },
  { iata: "OKC", name: "Will Rogers World", city: "Oklahoma City", state: "OK", country: "US" },
  { iata: "MKE", name: "Milwaukee Mitchell International", city: "Milwaukee", state: "WI", country: "US" },
  { iata: "RNO", name: "Reno-Tahoe International", city: "Reno", state: "NV", country: "US" },
  { iata: "ABQ", name: "Albuquerque International Sunport", city: "Albuquerque", state: "NM", country: "US" },
  { iata: "OMA", name: "Eppley Airfield", city: "Omaha", state: "NE", country: "US" },
  { iata: "BUR", name: "Hollywood Burbank", city: "Burbank", state: "CA", country: "US" },
  { iata: "ANC", name: "Ted Stevens Anchorage International", city: "Anchorage", state: "AK", country: "US" },
  { iata: "SNA", name: "John Wayne Airport", city: "Santa Ana", state: "CA", country: "US" },
  { iata: "BDL", name: "Bradley International", city: "Hartford", state: "CT", country: "US" },
  { iata: "PBI", name: "Palm Beach International", city: "West Palm Beach", state: "FL", country: "US" },
  { iata: "MEM", name: "Memphis International", city: "Memphis", state: "TN", country: "US" },
  { iata: "BOI", name: "Boise Airport", city: "Boise", state: "ID", country: "US" },
  { iata: "BUF", name: "Buffalo Niagara International", city: "Buffalo", state: "NY", country: "US" },
  { iata: "ONT", name: "Ontario International", city: "Ontario", state: "CA", country: "US" },
  { iata: "TUS", name: "Tucson International", city: "Tucson", state: "AZ", country: "US" },
  { iata: "RIC", name: "Richmond International", city: "Richmond", state: "VA", country: "US" },
  { iata: "ORF", name: "Norfolk International", city: "Norfolk", state: "VA", country: "US" },
  { iata: "CLT", name: "Charlotte Douglas International", city: "Charlotte", state: "NC", country: "US" },
  { iata: "MDW", name: "Chicago Midway International", city: "Chicago", state: "IL", country: "US" },
  { iata: "BHM", name: "Birmingham-Shuttlesworth International", city: "Birmingham", state: "AL", country: "US" },
  { iata: "GEG", name: "Spokane International", city: "Spokane", state: "WA", country: "US" },
  { iata: "TUL", name: "Tulsa International", city: "Tulsa", state: "OK", country: "US" },
  { iata: "DSM", name: "Des Moines International", city: "Des Moines", state: "IA", country: "US" },
  { iata: "ELP", name: "El Paso International", city: "El Paso", state: "TX", country: "US" },
  { iata: "LIT", name: "Bill and Hillary Clinton National", city: "Little Rock", state: "AR", country: "US" },
  { iata: "PVD", name: "T.F. Green International", city: "Providence", state: "RI", country: "US" },
  { iata: "CHS", name: "Charleston International", city: "Charleston", state: "SC", country: "US" },
  { iata: "GSP", name: "Greenville-Spartanburg International", city: "Greenville", state: "SC", country: "US" },
  { iata: "OGG", name: "Kahului Airport", city: "Kahului", state: "HI", country: "US" },
  { iata: "KOA", name: "Ellison Onizuka Kona International", city: "Kona", state: "HI", country: "US" },
  { iata: "LIH", name: "Lihue Airport", city: "Lihue", state: "HI", country: "US" },
  { iata: "PSP", name: "Palm Springs International", city: "Palm Springs", state: "CA", country: "US" },
  { iata: "SYR", name: "Syracuse Hancock International", city: "Syracuse", state: "NY", country: "US" },
  { iata: "ALB", name: "Albany International", city: "Albany", state: "NY", country: "US" },
  { iata: "ICT", name: "Wichita Dwight D. Eisenhower National", city: "Wichita", state: "KS", country: "US" },
  { iata: "SDF", name: "Louisville Muhammad Ali International", city: "Louisville", state: "KY", country: "US" },
  { iata: "PWM", name: "Portland International Jetport", city: "Portland", state: "ME", country: "US" },
  { iata: "GSO", name: "Piedmont Triad International", city: "Greensboro", state: "NC", country: "US" },
  { iata: "SAV", name: "Savannah/Hilton Head International", city: "Savannah", state: "GA", country: "US" },
  { iata: "MSN", name: "Dane County Regional", city: "Madison", state: "WI", country: "US" },
  { iata: "MYR", name: "Myrtle Beach International", city: "Myrtle Beach", state: "SC", country: "US" },
  { iata: "LEX", name: "Blue Grass Airport", city: "Lexington", state: "KY", country: "US" },
  { iata: "HSV", name: "Huntsville International", city: "Huntsville", state: "AL", country: "US" },
  { iata: "FAT", name: "Fresno Yosemite International", city: "Fresno", state: "CA", country: "US" },
  { iata: "XNA", name: "Northwest Arkansas National", city: "Fayetteville", state: "AR", country: "US" },
  { iata: "PNS", name: "Pensacola International", city: "Pensacola", state: "FL", country: "US" },
  { iata: "CAE", name: "Columbia Metropolitan", city: "Columbia", state: "SC", country: "US" },
  { iata: "SRQ", name: "Sarasota-Bradenton International", city: "Sarasota", state: "FL", country: "US" },
  { iata: "DAY", name: "James M. Cox Dayton International", city: "Dayton", state: "OH", country: "US" },
  { iata: "BTV", name: "Burlington International", city: "Burlington", state: "VT", country: "US" },
  { iata: "GRR", name: "Gerald R. Ford International", city: "Grand Rapids", state: "MI", country: "US" },
  { iata: "FNT", name: "Bishop International", city: "Flint", state: "MI", country: "US" },
  { iata: "MAF", name: "Midland International Air and Space Port", city: "Midland", state: "TX", country: "US" },
  { iata: "AVL", name: "Asheville Regional", city: "Asheville", state: "NC", country: "US" },
  { iata: "FAI", name: "Fairbanks International", city: "Fairbanks", state: "AK", country: "US" },

  // Canada
  { iata: "YYZ", name: "Toronto Pearson International", city: "Toronto", country: "Canada" },
  { iata: "YVR", name: "Vancouver International", city: "Vancouver", country: "Canada" },
  { iata: "YUL", name: "Montréal-Trudeau International", city: "Montreal", country: "Canada" },
  { iata: "YYC", name: "Calgary International", city: "Calgary", country: "Canada" },
  { iata: "YEG", name: "Edmonton International", city: "Edmonton", country: "Canada" },
  { iata: "YOW", name: "Ottawa Macdonald-Cartier International", city: "Ottawa", country: "Canada" },
  { iata: "YWG", name: "Winnipeg James Armstrong Richardson International", city: "Winnipeg", country: "Canada" },
  { iata: "YHZ", name: "Halifax Stanfield International", city: "Halifax", country: "Canada" },

  // Mexico & Caribbean
  { iata: "MEX", name: "Mexico City International", city: "Mexico City", country: "Mexico" },
  { iata: "CUN", name: "Cancún International", city: "Cancún", country: "Mexico" },
  { iata: "GDL", name: "Guadalajara International", city: "Guadalajara", country: "Mexico" },
  { iata: "SJD", name: "Los Cabos International", city: "San José del Cabo", country: "Mexico" },
  { iata: "PVR", name: "Puerto Vallarta International", city: "Puerto Vallarta", country: "Mexico" },
  { iata: "MBJ", name: "Sangster International", city: "Montego Bay", country: "Jamaica" },
  { iata: "NAS", name: "Lynden Pindling International", city: "Nassau", country: "Bahamas" },
  { iata: "PUJ", name: "Punta Cana International", city: "Punta Cana", country: "Dominican Republic" },

  // Europe
  { iata: "LHR", name: "London Heathrow", city: "London", country: "United Kingdom" },
  { iata: "LGW", name: "London Gatwick", city: "London", country: "United Kingdom" },
  { iata: "CDG", name: "Charles de Gaulle", city: "Paris", country: "France" },
  { iata: "AMS", name: "Amsterdam Schiphol", city: "Amsterdam", country: "Netherlands" },
  { iata: "FRA", name: "Frankfurt Airport", city: "Frankfurt", country: "Germany" },
  { iata: "MUC", name: "Munich Airport", city: "Munich", country: "Germany" },
  { iata: "MAD", name: "Adolfo Suárez Madrid-Barajas", city: "Madrid", country: "Spain" },
  { iata: "BCN", name: "Barcelona-El Prat", city: "Barcelona", country: "Spain" },
  { iata: "FCO", name: "Leonardo da Vinci-Fiumicino", city: "Rome", country: "Italy" },
  { iata: "MXP", name: "Milan Malpensa", city: "Milan", country: "Italy" },
  { iata: "LIS", name: "Lisbon Humberto Delgado", city: "Lisbon", country: "Portugal" },
  { iata: "ZRH", name: "Zurich Airport", city: "Zurich", country: "Switzerland" },
  { iata: "VIE", name: "Vienna International", city: "Vienna", country: "Austria" },
  { iata: "CPH", name: "Copenhagen Kastrup", city: "Copenhagen", country: "Denmark" },
  { iata: "OSL", name: "Oslo Gardermoen", city: "Oslo", country: "Norway" },
  { iata: "ARN", name: "Stockholm Arlanda", city: "Stockholm", country: "Sweden" },
  { iata: "HEL", name: "Helsinki-Vantaa", city: "Helsinki", country: "Finland" },
  { iata: "DUB", name: "Dublin Airport", city: "Dublin", country: "Ireland" },
  { iata: "EDI", name: "Edinburgh Airport", city: "Edinburgh", country: "United Kingdom" },
  { iata: "BRU", name: "Brussels Airport", city: "Brussels", country: "Belgium" },
  { iata: "ATH", name: "Athens International", city: "Athens", country: "Greece" },
  { iata: "IST", name: "Istanbul Airport", city: "Istanbul", country: "Turkey" },
  { iata: "WAW", name: "Warsaw Chopin", city: "Warsaw", country: "Poland" },
  { iata: "PRG", name: "Václav Havel Airport Prague", city: "Prague", country: "Czech Republic" },
  { iata: "BUD", name: "Budapest Ferenc Liszt International", city: "Budapest", country: "Hungary" },
  { iata: "KEF", name: "Keflavík International", city: "Reykjavik", country: "Iceland" },

  // Asia & Middle East
  { iata: "NRT", name: "Narita International", city: "Tokyo", country: "Japan" },
  { iata: "HND", name: "Tokyo Haneda", city: "Tokyo", country: "Japan" },
  { iata: "ICN", name: "Incheon International", city: "Seoul", country: "South Korea" },
  { iata: "PEK", name: "Beijing Capital International", city: "Beijing", country: "China" },
  { iata: "PVG", name: "Shanghai Pudong International", city: "Shanghai", country: "China" },
  { iata: "HKG", name: "Hong Kong International", city: "Hong Kong", country: "China" },
  { iata: "SIN", name: "Singapore Changi", city: "Singapore", country: "Singapore" },
  { iata: "BKK", name: "Suvarnabhumi Airport", city: "Bangkok", country: "Thailand" },
  { iata: "DEL", name: "Indira Gandhi International", city: "New Delhi", country: "India" },
  { iata: "BOM", name: "Chhatrapati Shivaji Maharaj International", city: "Mumbai", country: "India" },
  { iata: "DXB", name: "Dubai International", city: "Dubai", country: "UAE" },
  { iata: "AUH", name: "Abu Dhabi International", city: "Abu Dhabi", country: "UAE" },
  { iata: "DOH", name: "Hamad International", city: "Doha", country: "Qatar" },
  { iata: "TLV", name: "Ben Gurion International", city: "Tel Aviv", country: "Israel" },
  { iata: "KUL", name: "Kuala Lumpur International", city: "Kuala Lumpur", country: "Malaysia" },
  { iata: "MNL", name: "Ninoy Aquino International", city: "Manila", country: "Philippines" },
  { iata: "TPE", name: "Taiwan Taoyuan International", city: "Taipei", country: "Taiwan" },
  { iata: "CGK", name: "Soekarno-Hatta International", city: "Jakarta", country: "Indonesia" },
  { iata: "DPS", name: "Ngurah Rai International", city: "Bali", country: "Indonesia" },
  { iata: "HAN", name: "Noi Bai International", city: "Hanoi", country: "Vietnam" },
  { iata: "SGN", name: "Tan Son Nhat International", city: "Ho Chi Minh City", country: "Vietnam" },

  // Oceania
  { iata: "SYD", name: "Sydney Kingsford Smith", city: "Sydney", country: "Australia" },
  { iata: "MEL", name: "Melbourne Tullamarine", city: "Melbourne", country: "Australia" },
  { iata: "BNE", name: "Brisbane Airport", city: "Brisbane", country: "Australia" },
  { iata: "AKL", name: "Auckland Airport", city: "Auckland", country: "New Zealand" },

  // South America
  { iata: "GRU", name: "São Paulo-Guarulhos International", city: "São Paulo", country: "Brazil" },
  { iata: "GIG", name: "Rio de Janeiro-Galeão International", city: "Rio de Janeiro", country: "Brazil" },
  { iata: "EZE", name: "Ministro Pistarini International", city: "Buenos Aires", country: "Argentina" },
  { iata: "SCL", name: "Arturo Merino Benítez International", city: "Santiago", country: "Chile" },
  { iata: "BOG", name: "El Dorado International", city: "Bogotá", country: "Colombia" },
  { iata: "LIM", name: "Jorge Chávez International", city: "Lima", country: "Peru" },
  { iata: "PTY", name: "Tocumen International", city: "Panama City", country: "Panama" },
  { iata: "UIO", name: "Mariscal Sucre International", city: "Quito", country: "Ecuador" },

  // Africa
  { iata: "JNB", name: "O.R. Tambo International", city: "Johannesburg", country: "South Africa" },
  { iata: "CPT", name: "Cape Town International", city: "Cape Town", country: "South Africa" },
  { iata: "CAI", name: "Cairo International", city: "Cairo", country: "Egypt" },
  { iata: "NBO", name: "Jomo Kenyatta International", city: "Nairobi", country: "Kenya" },
  { iata: "CMN", name: "Mohammed V International", city: "Casablanca", country: "Morocco" },
  { iata: "ADD", name: "Bole International", city: "Addis Ababa", country: "Ethiopia" },
];
